title: Querydsl
description: >-
  Type-safe SQL-like queries for Java â€” JPA, SQL, MongoDB, R2DBC, Collections, and more.
url: "https://openfeign.github.io"
baseurl: "/querydsl"

remote_theme: just-the-docs/just-the-docs@v0.10.0

querydsl_version: "7.1"
group_id: "io.github.openfeign.querydsl"

permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

search_enabled: true

heading_anchors: true

nav_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  GitHub:
    - "https://github.com/OpenFeign/querydsl"
  Maven Central:
    - "https://central.sonatype.com/namespace/io.github.openfeign.querydsl"

aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/OpenFeign/querydsl"
gh_edit_branch: "master"
gh_edit_source: "docs"
gh_edit_view_mode: "edit"

footer_content: >-
  Copyright &copy; 2007&ndash;2026 Querydsl team. Maintained by the
  <a href="https://github.com/OpenFeign/querydsl">OpenFeign community</a>.
  Distributed under the
  <a href="https://github.com/OpenFeign/querydsl/blob/master/LICENSE">Apache License 2.0</a>.

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
